### PR TITLE
Remove calls to log.Println

### PR DESCRIPTION
**Pull request by kisielk**

### CODE REVIEW

**Comment by kisielk** [comment]
These end up spamming the stdout of my app and don't actually provide any useful information.

**Comment by eduncan911** [comment]
Logging should be directed to stderr by default, not stdout.  If it is spamming stdout, then I'd suggest looking at how logging is setup for the app and submit a pull request for that.

I highly recommend leaving these "debug" statements, as that is exactly what they are.

If they are spamming your console, and they are indeed being outputted to stderr like they should, then just ignore them.

   2>/dev/null

**Comment by kisielk** [comment]
stderr or whatever, these messages provide no use and there's no method to turn them off in this library. The go log package doesn't provide a way to filter out log messages from different sources, and if I am using it in my application to log actual useful output there's no point in cluttering it up with messages that provide no value.

For example why do I need it to log that hid_init is being called?

**Comment by GeertJohan** [comment]
What do you think about a `var DebugLogger func(log string)` that is set to discard logs by default and can be overrided to print them to stdout, stderr, or whatever? @kisielk @eduncan911

**Comment by eduncan911** [comment]
I've gone through quite a lot of "package-level" logging patterns myself as I am serious advocate for logging (that's why I chimed in to begin with :+1: ):

http://go-talks.appspot.com/github.com/eduncan911/goslides/gologit.slide#1  

What I find best, that allows the consuming executable to just completely ignore logging if they wish, is to allow it to be injected into the constructor using D.I. principals.  For example, a quick and dirty hack (which I don't recommend, but shows the point):

    // go/hid package change
    
    // global var
    var _logger *log.Logger
    
    // note the variadic parameter at the end, making it optional
    func Open(vendorId uint16, productId uint16, serialNumber string, logger ...log.Logger) (*Device, error) {
      ...
      for _, debugLogger := range logger {
        // set global logger
        _logger = &debugLogger
      }
    }

The for loop is only executed when the variadic parameter is set (a trick I use).

Then the consuming code can safely ignore it, which doesn't break existing consumers:

    // ignored, and doesn't break existing codebases
    leds, err := hid.Open(0x1770, 0xff00, "")

And here's an example of using the optional debugger:

    // create a logger
    myDebugLogger := ...
    
    // pass it in last
    leds, err := hid.Open(0x1770, 0xff00, "", myDebugLogger)

Personally though, I like Rob Pike's functional parameters blog post about the pattern others have come up with:

http://commandcenter.blogspot.com/2014/01/self-referential-functions-and-design.html

The key to this pattern is it allows you to add additional options in the future without breaking APIs.

I have been using this "Function Parameters" personally in all of my projects and at work.  People really like having things available in intellisense.

Problem is, it usually breaks existing codebases that didn't start that way.

For `go.hid`, I would suggest tweaking `hid.Open()` to allow these optional parameters to be passed in.  This would keep existing consumers from breaking, without making the API overly complex with additional `New()`-like constructors.  K.I.S.S. it, right?

I'd do something like this...

    var _logger *log.Logger
    
    func Open(vendorId uint16, productId uint16, serialNumber string, options ...func(*Device)) (*Device, error) {
        ...
        // instantiate as normal
        dev := &Device{
            hidHandle: hidHandle,
        }
    
        // now, set the user-defined options on the device
        for _, option := range options {
            option(dev)
        }
    
        // done
        return dev, nil
    }
    
    ...
    
    // Logger sets the internal instance for logging
    func (dev *Device) SetLogger(logger *log.Logger) {
        // currently global as the package seems to support only 1 device
        _logger = logger
    }
    
    // log is our own internal `log()` method that safely sets, or not set, log messages:
    func log(msg string, args ...interface{}) {
        if _logger == nil {
            return
        }

        m := msg
        if len(args) > 0 {
            m = fmt.Sprintf(m, args...)
        }
        logger.Println(m)
    }

This keeps backwards compatibility with existing consumers:

    leds, err := hid.Open(0x1770, 0xff00, "")

... while allowing new consumers to set a custom logger (that adheres to Golang's builtin `log` package, which almost all do anyways):

    opts := func(d *hid.Device) {
        d.SetLogger(...myCustomLogger...or...nil...)
    }
    leds, err := hid.Open(0x1770, 0xff00, "", opts)

What I like about this pattern is that you can add additional configurations to the `Device` via set functions without changing the API.  For example, setting a timeout perhaps?

If you'd like a PR, I can throw something together like this...

**Comment by kisielk** [comment]
Personally I think that's totally over-engineering it. Why would you need to pass options in to the Open function of the device when it already returns a *Device and you can just call functions on that? Also the logger could just as easily be a member of the Device struct, and if it's nil then no logging is performed. Still currently the package only logs in 3 places and none of them provide any useful information, so what's the point of even designing for this? Logging is mostly the domain of the application and the package can communicate any errors through return values which the caller can decide to log or not.

**Comment by eduncan911** [comment]
You should see have seen my first pass, with New, OpenWithConfig and all.
 :)

The point of this was to allow for additional options I was thinking, like
timeouts and event hooks/filtering.

But yeah, if you never use it for anything else but logging, then there's
no point.

**Comment by GeertJohan** [comment]
Yeah this definitly shouldn't be too complicated. There could be a logger per-device, but nothing more fancy than that. But for now I agree with kisielk that these messages don't provide enough information to be worth logging. I'm still open to a logging/debugging solution, but it should come with log calls that provide more and detailed information.

Will merge this PR for now to solve kisielk's problem. A package shouldn't write to stdout/stderr (with the ocasional in-development exception).

**Pull request merged**
